replacements = "github.com/davidsneighbour/hugo-monologue -> ../../hugo-monologue"

[[imports]]
path = "github.com/davidsneighbour/hugo-monologue"
disable = false
ignoreConfig = false
ignoreImports = false
